[general]
bars = 24
framerate = 30
autosens = 1
sensitivity = 100

[input]
method = pulse
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 8

[smoothing]
monstercat = 1
waves = 0
gravity = 70
noise_reduction = 77
