[audio]
enable_overdrive = false
enable_sounds = true

[bar.default]
border = "secondary"
border_width = 2.0
center = [ "privacy", "clock" ]
concave_edge_corners = false
end = [ "media", "cpu", "tray", "network", "bluetooth", "volume", "brightness", "battery" ]
font_family = "JetBrainsMono Nerd Font"
hover_highlight = false
margin_edge = 6
margin_ends = 6
panel_overlap = 0
position = "bottom"
radius = 0
shadow = false
start = [ "launcher", "workspaces", "audio_visualizer", "active_window" ]

[battery]
warning_threshold = 20

[brightness]
minimum_brightness = 0.04999999888241291

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

    [calendar.account.xulqarnaen]
    name = "ibr"
    type = "google"

[control_center]
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false
    show_week_numbers = true

[desktop_widgets]
enabled = false

[dock]
background_opacity = 0.99999997764825821
border = "secondary"
border_width = 2.0
concave_edge_corners = false
cross_axis_padding = 5
enabled = false
icon_size = 40
inactive_opacity = 0.99999997764825821
item_spacing = 5
launcher_icon = "brand-bumble"
launcher_position = "start"
magnification_scale = 1.7500000111758709
main_axis_padding = 0
margin_edge = 6
pinned = [
    "foot",
    "org.gnome.Evince",
    "org.gnome.Nautilus",
    "brave-origin",
    "Photos",
    "org.telegram.desktop",
    "YouTube Music",
    "Calendar"
]
position = "right"
radius = 0
shadow = false
show_dots = true

[location]
address = "Srinagar"

[lockscreen]
blur_intensity = 0.0
fingerprint = false
tint_intensity = 0.0
transition = []

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 683.0
    cy = 598.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 72.0
    box_width = 720.0
    cx = 683.0
    cy = 552.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        bands = 32
        show_when_idle = true

[notification]
background_opacity = 0.99999997764825821

[osd]
background_opacity = 0.99999997764825821

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true

[plugins]
enabled = [ "noctalia/screen_recorder" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
app_icon_color = "outline"
avatar_path = "/home/ibr/Pictures/Wallpapers/wallhaven-8g8kmo_1920x1080.png"
button_borders = false
card_borders = false
clipboard_auto_paste = "ctrl_v"
corner_radius_scale = 0.0
font_family = "JetBrainsMono Nerd Font"
input_borders = false
password_style = "random"
polkit_agent = true
popup_borders = false
popup_shadows = false
screen_time_enabled = true
telemetry_enabled = true

    [shell.animation]
    enabled = true

    [shell.launcher]
    categories = false
    show_icons = false
    sort_by_usage = false

    [shell.panel]
    borders = false
    clipboard_placement = "floating"
    clipboard_position = "center"
    control_center_placement = "floating"
    open_near_click_clipboard = false
    open_near_click_control_center = true
    session_placement = "floating"
    wallpaper_placement = "floating"

    [shell.screenshot]
    directory = "~/Pictures/Screenshots"

[theme]
builtin = "Gruvbox"
community_palette = "Cyberpunk"
custom_palette = "solitude2"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "foot", "gtk3", "gtk4", "hyprland", "kcolorscheme", "qt", "starship" ]
    community_ids = [ "telegram", "neovim" ]

        [theme.templates.user.nvim_base16]
        input_path = "~/.config/nvim/lua/matugen-template.lua"
        output_path = "~/.config/nvim/lua/matugen.lua"
        post_hook = "pkill -SIGUSR1 nvim"

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/ibr/Pictures/Wallpapers/wallhaven-8g8kmo_1920x1080.png"

    [wallpaper.last]
    path = "/home/ibr/Pictures/Wallpapers/wallhaven-8g8kmo_1920x1080.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/ibr/Pictures/Wallpapers/wallhaven-8g8kmo_1920x1080.png"

    [[wallpaper.favorite]]
    path = "/home/ibr/Pictures/Wallpapers/wallhaven-5ypg11_1920x1080.png"

[widget.active_window]
capsule_fill = "tertiary"
display = "text_only"
title_scroll = "on_hover"

[widget.audio_visualizer]
mirrored = false
reversed = true

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "%I:%M %p - %A, %B %d"
vertical_format = "%I:%M %p"

[widget.cpu]
show_glyph = false
stat = "ram_used"
visualization = "none"

[widget.launcher]
glyph = "brand-bumble"

[widget.media]
artist_first = true
hide_album_art = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.privacy]
hide_inactive = true

[widget.session]
anchor = true

[widget.volume]
show_label = false

[widget.workspaces]
style = "minimal"
